spring.application.name: pida-server
spring.profiles.active: local

spring:
  config:
    import:
      - redis.yml
      - logging.yml
      - monitoring.yml
#      - authentication-redis.yml
#      - authentication.yml
#      - db-core.yml
#      - notification.yml
#      - aws.yml
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  servlet:
    encoding:
      charset: UTF-8
      force: true
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - swagger.yml
---
spring:
  config:
    activate:
      on-profile: prod
---
