spring:
  cloud:
    discovery:
      enabled: false
    openfeign:
      client:
        config:
          kakao-map-api:
            connectTimeout: 1000
            readTimeout: 2000
            loggerLevel: full
          # 추후 naver map api 연동 예정
  compression:
    response:
      enabled: false
  httpclient:
    max-connections: 2000
    max-connections-per-route: 500

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
