services:
  backend:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
    network_mode: host
    env_file:
      - ~/.env
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 768M
        reservations:
          cpus: '0.20'
          memory: 256M
  redis:
    image: redis:7.2-alpine
    container_name: p-local-redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    network_mode: "host"
    volumes:
      - /opt/redis/data:/data
      - /opt/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 64M
        reservations:
          cpus: '0.10'
          memory: 32M
