services:
  db:
    image: mysql:8.0.36
    container_name: pida-local-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pida
      MYSQL_USER: pida
      MYSQL_PASSWORD: pida!@
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci" ]
