spring:
  cache:
    type: redis
---
spring:
  config:
    activate:
      on-profile: local
auth:
  datasource:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: dev
auth:
  datasource:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
---
spring:
  config:
    activate:
      on-profile: live
auth:
  datasource:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
