spring:
  cloud:
    discovery:
      enabled: false
    openfeign:
      client:
        config:
          airkorea-air-quality-api:
            connectTimeout: 1000
            readTimeout: 3000
            loggerLevel: full
          airkorea-station-api:
            connectTimeout: 1000
            readTimeout: 3000
            loggerLevel: full

airkorea:
  api:
    air-quality-base-url: ${AIR_KOREA_AIR_QUALITY_API_BASE_URL:http://apis.data.go.kr/B552584/ArpltnInforInqireSvc}
    air-quality-service-key: ${AIR_KOREA_AIR_QUALITY_API_SERVICE_KEY:${AIR_KOREA_API_SERVICE_KEY:}}
    station-base-url: ${AIR_KOREA_STATION_API_BASE_URL:http://apis.data.go.kr/B552584/MsrstnInfoInqireSvc}
    station-service-key: ${AIR_KOREA_STATION_API_SERVICE_KEY:${AIR_KOREA_API_SERVICE_KEY:}}
